import {GlobalStyles} from "@/app/page";
import CartContextProvider from "@/components/CartContext";
import Header from "@/components/Header";


export const metadata = {
  title: 'E-commerce Front',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
      <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"/>
      </head>

      <body>

      <GlobalStyles/>
      <CartContextProvider>
      <Header/>
      {children}
      </CartContextProvider>
      

      </body>
    </html>
  )
}
